---
clone:
  depth: 1
kind: pipeline
name: WHYRED
steps:
  - name: val
    image: azrim89/kernel:latest
    commands:
      - curl https://raw.githubusercontent.com/Reinazhard/myscripts/master/clang-4.19.sh | bash
    environment:
      TELEGRAM_TOKEN:
        from_secret: BOT_API_KEY

---
clone:
  depth: 1
kind: pipeline
name: TULIP
steps:
  - name: val
    image: azrim89/kernel:latest
    commands:
      - curl https://raw.githubusercontent.com/Reinazhard/myscripts/master/tulip-4.19-clang.sh | bash
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
